#!/usr/bin/env python3
__author__ = 'zeemi'
emtpy_tweet = r'\n'
disconnect_msg = r'''{
                  "disconnect":{
                    "code": 4,
                    "stream_name":"",
                    "reason":""
                  }
                }'''

raw_tweet = r'''{"created_at": "Wed Apr 20 23:17:17 +0000 2016", "id": 722927145476091905, "id_str": "722927145476091905",
             "text": "RT @mertkoseoglu: Bi g\u00fcl\u00fc\u015f\u00fc var... https:\/\/t.co\/o4upWlbzOP",
             "source": "\u003ca href=\"http:\/\/www.twitter.com\" rel=\"nofollow\"\u003eTwitter for Windows Phone\u003c\/a\u003e",
             "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null,
             "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null,
             "user": {"id": 3398774578, "id_str": "3398774578", "name": "EDA", "screen_name": "cicilibirkiz",
                      "location": null, "url": null, "description": "Bilmiyorum", "protected": false, "verified": false,
                      "followers_count": 87063, "friends_count": 71020, "listed_count": 15, "favourites_count": 8358,
                      "statuses_count": 23829, "created_at": "Sat Aug 01 13:40:02 +0000 2015", "utc_offset": -25200,
                      "time_zone": "Pacific Time (US & Canada)", "geo_enabled": false, "lang": "tr",
                      "contributors_enabled": false, "is_translator": false, "profile_background_color": "FF6699",
                      "profile_background_image_url": "http:\/\/abs.twimg.com\/images\/themes\/theme11\/bg.gif",
                      "profile_background_image_url_https": "https:\/\/abs.twimg.com\/images\/themes\/theme11\/bg.gif",
                      "profile_background_tile": true, "profile_link_color": "B40B43",
                      "profile_sidebar_border_color": "CC3366", "profile_sidebar_fill_color": "E5507E",
                      "profile_text_color": "362720", "profile_use_background_image": true,
                      "profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/670223360253644800\/zpx3ykWr_normal.jpg",
                      "profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/670223360253644800\/zpx3ykWr_normal.jpg",
                      "profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/3398774578\/1438439819",
                      "default_profile": false, "default_profile_image": false, "following": null,
                      "follow_request_sent": null, "notifications": null}, "geo": null, "coordinates": null,
             "place": null, "contributors": null,
             "retweeted_status": {"created_at": "Tue Nov 03 10:39:28 +0000 2015", "id": 661492887465672704,
                                  "id_str": "661492887465672704",
                                  "text": "Bi g\u00fcl\u00fc\u015f\u00fc var... https:\/\/t.co\/o4upWlbzOP",
                                  "source": "\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
                                  "truncated": false, "in_reply_to_status_id": null, "in_reply_to_status_id_str": null,
                                  "in_reply_to_user_id": null, "in_reply_to_user_id_str": null,
                                  "in_reply_to_screen_name": null,
                                  "user": {"id": 30623557, "id_str": "30623557", "name": "mert kors",
                                           "screen_name": "mertkoseoglu", "location": null,
                                           "url": "http:\/\/Instagr.am\/koseoglumert",
                                           "description": "\u015fimdilerde m\u00fctevazi bir ya\u015fam s\u00fcrmekte olan eski superstar snapchat:mertkoseoglu",
                                           "protected": false, "verified": false, "followers_count": 26535,
                                           "friends_count": 373, "listed_count": 38, "favourites_count": 6770,
                                           "statuses_count": 3142, "created_at": "Sun Apr 12 08:22:26 +0000 2009",
                                           "utc_offset": 10800, "time_zone": "Istanbul", "geo_enabled": true,
                                           "lang": "tr", "contributors_enabled": false, "is_translator": false,
                                           "profile_background_color": "03072D",
                                           "profile_background_image_url": "http:\/\/pbs.twimg.com\/profile_background_images\/787160355\/3ccf30a1889821466eedc3526fb2d5d3.jpeg",
                                           "profile_background_image_url_https": "https:\/\/pbs.twimg.com\/profile_background_images\/787160355\/3ccf30a1889821466eedc3526fb2d5d3.jpeg",
                                           "profile_background_tile": false, "profile_link_color": "A7394D",
                                           "profile_sidebar_border_color": "16818E",
                                           "profile_sidebar_fill_color": "030516", "profile_text_color": "16818E",
                                           "profile_use_background_image": true,
                                           "profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/682960269048426497\/11N7D9x1_normal.jpg",
                                           "profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/682960269048426497\/11N7D9x1_normal.jpg",
                                           "profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/30623557\/1458494403",
                                           "default_profile": false, "default_profile_image": false, "following": null,
                                           "follow_request_sent": null, "notifications": null}, "geo": null,
                                  "coordinates": null, "place": null, "contributors": null, "is_quote_status": false,
                                  "retweet_count": 1104, "favorite_count": 1816,
                                  "entities": {"hashtags": [], "urls": [], "user_mentions": [], "symbols": [],
                                               "media": [{"id": 661492865852432384, "id_str": "661492865852432384",
                                                          "indices": [17, 40],
                                                          "media_url": "http:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg",
                                                          "media_url_https": "https:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg",
                                                          "url": "https:\/\/t.co\/o4upWlbzOP",
                                                          "display_url": "pic.twitter.com\/o4upWlbzOP",
                                                          "expanded_url": "http:\/\/twitter.com\/mertkoseoglu\/status\/661492887465672704\/photo\/1",
                                                          "type": "photo",
                                                          "sizes": {"thumb": {"w": 150, "h": 150, "resize": "crop"},
                                                                    "medium": {"w": 600, "h": 800, "resize": "fit"},
                                                                    "large": {"w": 768, "h": 1024, "resize": "fit"},
                                                                    "small": {"w": 340, "h": 453, "resize": "fit"}}}]},
                                  "extended_entities": {"media": [
                                      {"id": 661492865852432384, "id_str": "661492865852432384", "indices": [17, 40],
                                       "media_url": "http:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg",
                                       "media_url_https": "https:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg",
                                       "url": "https:\/\/t.co\/o4upWlbzOP",
                                       "display_url": "pic.twitter.com\/o4upWlbzOP",
                                       "expanded_url": "http:\/\/twitter.com\/mertkoseoglu\/status\/661492887465672704\/photo\/1",
                                       "type": "photo", "sizes": {"thumb": {"w": 150, "h": 150, "resize": "crop"},
                                                                  "medium": {"w": 600, "h": 800, "resize": "fit"},
                                                                  "large": {"w": 768, "h": 1024, "resize": "fit"},
                                                                  "small": {"w": 340, "h": 453, "resize": "fit"}}}]},
                                  "favorited": false, "retweeted": false, "possibly_sensitive": false,
                                  "filter_level": "low", "lang": "tr"}, "is_quote_status": false, "retweet_count": 0,
             "favorite_count": 0, "entities": {"hashtags": [], "urls": [], "user_mentions": [
        {"screen_name": "mertkoseoglu", "name": "mert kors", "id": 30623557, "id_str": "30623557", "indices": [3, 16]}],
                                               "symbols": [], "media": [
            {"id": 661492865852432384, "id_str": "661492865852432384", "indices": [35, 58],
             "media_url": "http:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg",
             "media_url_https": "https:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg",
             "url": "https:\/\/t.co\/o4upWlbzOP", "display_url": "pic.twitter.com\/o4upWlbzOP",
             "expanded_url": "http:\/\/twitter.com\/mertkoseoglu\/status\/661492887465672704\/photo\/1",
             "type": "photo",
             "sizes": {"thumb": {"w": 150, "h": 150, "resize": "crop"}, "medium": {"w": 600, "h": 800, "resize": "fit"},
                       "large": {"w": 768, "h": 1024, "resize": "fit"}, "small": {"w": 340, "h": 453, "resize": "fit"}},
             "source_status_id": 661492887465672704, "source_status_id_str": "661492887465672704",
             "source_user_id": 30623557, "source_user_id_str": "30623557"}]}, "extended_entities": {"media": [
        {"id": 661492865852432384, "id_str": "661492865852432384", "indices": [35, 58],
         "media_url": "http:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg",
         "media_url_https": "https:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg", "url": "https:\/\/t.co\/o4upWlbzOP",
         "display_url": "pic.twitter.com\/o4upWlbzOP",
         "expanded_url": "http:\/\/twitter.com\/mertkoseoglu\/status\/661492887465672704\/photo\/1", "type": "photo",
         "sizes": {"thumb": {"w": 150, "h": 150, "resize": "crop"}, "medium": {"w": 600, "h": 800, "resize": "fit"},
                   "large": {"w": 768, "h": 1024, "resize": "fit"}, "small": {"w": 340, "h": 453, "resize": "fit"}},
         "source_status_id": 661492887465672704, "source_status_id_str": "661492887465672704",
         "source_user_id": 30623557, "source_user_id_str": "30623557"}]}, "favorited": false, "retweeted": false,
             "possibly_sensitive": false, "filter_level": "low", "lang": "tr", "timestamp_ms": "1461194237475"}'''