__author__ = 'zeemi'
emtpy_tweet ='\n'
# raw_tweet = '''{"created_at":"Wed Apr 20 19:33:46 +0000 2016","id":722870897099542528,"id_str":"722870897099542528","text":"RT @gudaricatala1: Un profesor de Religi\u00f3n de #Murcia no ir\u00e1 a prisi\u00f3n a pesar de admitir que viol\u00f3 a nueve menores @jcmata233 @_ju1_  http\u2026","source":"\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":4063190715,"id_str":"4063190715","name":"Gonzalo Prieto","screen_name":"PrietoSport","location":null,"url":null,"description":"\u201c- Has aprendido dos cosas muy importantes. \n- \u00bfCu\u00e1les? \n- Pues, no traicionar a un amigo, y no irse nunca de la lengua.\u201d","protected":false,"verified":false,"followers_count":56,"friends_count":40,"listed_count":8,"favourites_count":1180,"statuses_count":5953,"created_at":"Wed Oct 28 21:12:59 +0000 2015","utc_offset":7200,"time_zone":"Madrid","geo_enabled":false,"lang":"es","contributors_enabled":false,"is_translator":false,"profile_background_color":"C0DEED","profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_tile":false,"profile_link_color":"0084B4","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/663443976985427968\/F8KdOfCN_normal.jpg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/663443976985427968\/F8KdOfCN_normal.jpg","profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/4063190715\/1447336705","default_profile":true,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"retweeted_status":{"created_at":"Wed Apr 20 19:31:55 +0000 2016","id":722870428771946496,"id_str":"722870428771946496","text":"Un profesor de Religi\u00f3n de #Murcia no ir\u00e1 a prisi\u00f3n a pesar de admitir que viol\u00f3 a nueve menores @jcmata233 @_ju1_  https:\/\/t.co\/vVfXy3dcPD","source":"\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":1129181233,"id_str":"1129181233","name":"@Gudaricatala1","screen_name":"gudaricatala1","location":"de Bar en calle.....Catalunya","url":null,"description":"S\u00f3lo los peces muertos siguen la corriente (periko solabarria) #28AkEreLibre #PerikoEredu #StopLeyMordaza #Desobediencia #stopDispersion #DDHH","protected":false,"verified":false,"followers_count":4000,"friends_count":2226,"listed_count":83,"favourites_count":6426,"statuses_count":60895,"created_at":"Mon Jan 28 20:46:25 +0000 2013","utc_offset":-36000,"time_zone":"Hawaii","geo_enabled":true,"lang":"es","contributors_enabled":false,"is_translator":false,"profile_background_color":"C0DEED","profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_tile":false,"profile_link_color":"0084B4","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/696772820769046528\/KNHqm6rj_normal.jpg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/696772820769046528\/KNHqm6rj_normal.jpg","profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/1129181233\/1449606673","default_profile":true,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":6,"favorite_count":2,"entities":{"hashtags":[{"text":"Murcia","indices":[27,34]}],"urls":[{"url":"https:\/\/t.co\/vVfXy3dcPD","expanded_url":"http:\/\/elventano.es\/2016\/04\/un-profesor-de-religion-de-murcia-no-ira-a-prision-a-pesar-de-admitir-que-violo-a-nueve-menores.html","display_url":"elventano.es\/2016\/04\/un-pro\u2026","indices":[116,139]}],"user_mentions":[{"screen_name":"jcmata233","name":"J C Mata","id":2218065063,"id_str":"2218065063","indices":[97,107]},{"screen_name":"_ju1_","name":"Profe #JeSuisYemen","id":1319390838,"id_str":"1319390838","indices":[108,114]}],"symbols":[]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"filter_level":"low","lang":"es"},"is_quote_status":false,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[{"text":"Murcia","indices":[46,53]}],"urls":[{"url":"https:\/\/t.co\/vVfXy3dcPD","expanded_url":"http:\/\/elventano.es\/2016\/04\/un-profesor-de-religion-de-murcia-no-ira-a-prision-a-pesar-de-admitir-que-violo-a-nueve-menores.html","display_url":"elventano.es\/2016\/04\/un-pro\u2026","indices":[139,140]}],"user_mentions":[{"screen_name":"gudaricatala1","name":"@Gudaricatala1","id":1129181233,"id_str":"1129181233","indices":[3,17]},{"screen_name":"jcmata233","name":"J C Mata","id":2218065063,"id_str":"2218065063","indices":[116,126]},{"screen_name":"_ju1_","name":"Profe #JeSuisYemen","id":1319390838,"id_str":"1319390838","indices":[127,133]}],"symbols":[]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"filter_level":"low","lang":"es","timestamp_ms":"1461180826817"}'''
raw_tweet = '{"created_at":"Wed Apr 20 23:17:17 +0000 2016","id":722927145476091905,"id_str":"722927145476091905","text":"RT @mertkoseoglu: Bi g\u00fcl\u00fc\u015f\u00fc var... https:\/\/t.co\/o4upWlbzOP","source":"\u003ca href=\"http:\/\/www.twitter.com\" rel=\"nofollow\"\u003eTwitter for Windows Phone\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":3398774578,"id_str":"3398774578","name":"EDA","screen_name":"cicilibirkiz","location":null,"url":null,"description":"Bilmiyorum","protected":false,"verified":false,"followers_count":87063,"friends_count":71020,"listed_count":15,"favourites_count":8358,"statuses_count":23829,"created_at":"Sat Aug 01 13:40:02 +0000 2015","utc_offset":-25200,"time_zone":"Pacific Time (US & Canada)","geo_enabled":false,"lang":"tr","contributors_enabled":false,"is_translator":false,"profile_background_color":"FF6699","profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme11\/bg.gif","profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme11\/bg.gif","profile_background_tile":true,"profile_link_color":"B40B43","profile_sidebar_border_color":"CC3366","profile_sidebar_fill_color":"E5507E","profile_text_color":"362720","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/670223360253644800\/zpx3ykWr_normal.jpg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/670223360253644800\/zpx3ykWr_normal.jpg","profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/3398774578\/1438439819","default_profile":false,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"retweeted_status":{"created_at":"Tue Nov 03 10:39:28 +0000 2015","id":661492887465672704,"id_str":"661492887465672704","text":"Bi g\u00fcl\u00fc\u015f\u00fc var... https:\/\/t.co\/o4upWlbzOP","source":"\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":30623557,"id_str":"30623557","name":"mert kors","screen_name":"mertkoseoglu","location":null,"url":"http:\/\/Instagr.am\/koseoglumert","description":"\u015fimdilerde m\u00fctevazi bir ya\u015fam s\u00fcrmekte olan eski superstar snapchat:mertkoseoglu","protected":false,"verified":false,"followers_count":26535,"friends_count":373,"listed_count":38,"favourites_count":6770,"statuses_count":3142,"created_at":"Sun Apr 12 08:22:26 +0000 2009","utc_offset":10800,"time_zone":"Istanbul","geo_enabled":true,"lang":"tr","contributors_enabled":false,"is_translator":false,"profile_background_color":"03072D","profile_background_image_url":"http:\/\/pbs.twimg.com\/profile_background_images\/787160355\/3ccf30a1889821466eedc3526fb2d5d3.jpeg","profile_background_image_url_https":"https:\/\/pbs.twimg.com\/profile_background_images\/787160355\/3ccf30a1889821466eedc3526fb2d5d3.jpeg","profile_background_tile":false,"profile_link_color":"A7394D","profile_sidebar_border_color":"16818E","profile_sidebar_fill_color":"030516","profile_text_color":"16818E","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/682960269048426497\/11N7D9x1_normal.jpg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/682960269048426497\/11N7D9x1_normal.jpg","profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/30623557\/1458494403","default_profile":false,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":1104,"favorite_count":1816,"entities":{"hashtags":[],"urls":[],"user_mentions":[],"symbols":[],"media":[{"id":661492865852432384,"id_str":"661492865852432384","indices":[17,40],"media_url":"http:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg","media_url_https":"https:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg","url":"https:\/\/t.co\/o4upWlbzOP","display_url":"pic.twitter.com\/o4upWlbzOP","expanded_url":"http:\/\/twitter.com\/mertkoseoglu\/status\/661492887465672704\/photo\/1","type":"photo","sizes":{"thumb":{"w":150,"h":150,"resize":"crop"},"medium":{"w":600,"h":800,"resize":"fit"},"large":{"w":768,"h":1024,"resize":"fit"},"small":{"w":340,"h":453,"resize":"fit"}}}]},"extended_entities":{"media":[{"id":661492865852432384,"id_str":"661492865852432384","indices":[17,40],"media_url":"http:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg","media_url_https":"https:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg","url":"https:\/\/t.co\/o4upWlbzOP","display_url":"pic.twitter.com\/o4upWlbzOP","expanded_url":"http:\/\/twitter.com\/mertkoseoglu\/status\/661492887465672704\/photo\/1","type":"photo","sizes":{"thumb":{"w":150,"h":150,"resize":"crop"},"medium":{"w":600,"h":800,"resize":"fit"},"large":{"w":768,"h":1024,"resize":"fit"},"small":{"w":340,"h":453,"resize":"fit"}}}]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"filter_level":"low","lang":"tr"},"is_quote_status":false,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[],"urls":[],"user_mentions":[{"screen_name":"mertkoseoglu","name":"mert kors","id":30623557,"id_str":"30623557","indices":[3,16]}],"symbols":[],"media":[{"id":661492865852432384,"id_str":"661492865852432384","indices":[35,58],"media_url":"http:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg","media_url_https":"https:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg","url":"https:\/\/t.co\/o4upWlbzOP","display_url":"pic.twitter.com\/o4upWlbzOP","expanded_url":"http:\/\/twitter.com\/mertkoseoglu\/status\/661492887465672704\/photo\/1","type":"photo","sizes":{"thumb":{"w":150,"h":150,"resize":"crop"},"medium":{"w":600,"h":800,"resize":"fit"},"large":{"w":768,"h":1024,"resize":"fit"},"small":{"w":340,"h":453,"resize":"fit"}},"source_status_id":661492887465672704,"source_status_id_str":"661492887465672704","source_user_id":30623557,"source_user_id_str":"30623557"}]},"extended_entities":{"media":[{"id":661492865852432384,"id_str":"661492865852432384","indices":[35,58],"media_url":"http:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg","media_url_https":"https:\/\/pbs.twimg.com\/media\/CS4YQbqW4AAcFFy.jpg","url":"https:\/\/t.co\/o4upWlbzOP","display_url":"pic.twitter.com\/o4upWlbzOP","expanded_url":"http:\/\/twitter.com\/mertkoseoglu\/status\/661492887465672704\/photo\/1","type":"photo","sizes":{"thumb":{"w":150,"h":150,"resize":"crop"},"medium":{"w":600,"h":800,"resize":"fit"},"large":{"w":768,"h":1024,"resize":"fit"},"small":{"w":340,"h":453,"resize":"fit"}},"source_status_id":661492887465672704,"source_status_id_str":"661492887465672704","source_user_id":30623557,"source_user_id_str":"30623557"}]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"filter_level":"low","lang":"tr","timestamp_ms":"1461194237475"}'


tweet = """{'id': 722453568121348096, 'extended_entities': {'media': [
    {'id': 722445452151537666, 'source_user_id': 3044644439, 'url': 'https://t.co/N36kmvfW2X', 'type': 'photo',
     'sizes': {'thumb': {'resize': 'crop', 'h': 150, 'w': 150}, 'medium': {'resize': 'fit', 'h': 352, 'w': 600},
               'small': {'resize': 'fit', 'h': 199, 'w': 340}, 'large': {'resize': 'fit', 'h': 601, 'w': 1024}},
     'source_user_id_str': '3044644439', 'source_status_id': 722445454856822784,
     'media_url': 'http://pbs.twimg.com/media/CgakT6EWwAIGX3L.jpg', 'indices': [143, 144],
     'expanded_url': 'http://twitter.com/hectorgeograph/status/722445454856822784/photo/1',
     'media_url_https': 'https://pbs.twimg.com/media/CgakT6EWwAIGX3L.jpg', 'display_url': 'pic.twitter.com/N36kmvfW2X',
     'id_str': '722445452151537666', 'source_status_id_str': '722445454856822784'}]}, 'geo': None,
         'text': 'RT @hectorgeograph: Computing the shortest path on an ellipsoid with Python. Geodesic lines &amp; GIS \nhttps://t.co/3MuJEib6Cu @cayetanobv http…',
         'retweeted': False, 'in_reply_to_screen_name': None, 'retweet_count': 0,
         'created_at': 'Tue Apr 19 15:55:27 +0000 2016', 'lang': 'en', 'in_reply_to_user_id': None,
         'filter_level': 'low',
         'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
         'favorite_count': 0, 'place': None, 'in_reply_to_status_id_str': None, 'truncated': False,
         'timestamp_ms': '1461081327835', 'is_quote_status': False, 'in_reply_to_user_id_str': None, 'favorited': False,
         'user': {'id': 426150795, 'profile_background_color': 'C0DEED', 'url': 'https://github.com/cayetanobv',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/426150795/1451315453',
                  'screen_name': 'cayetanobv', 'following': None, 'listed_count': 13, 'verified': False,
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'created_at': 'Thu Dec 01 22:11:53 +0000 2011', 'lang': 'es', 'profile_link_color': '0084B4',
                  'is_translator': False, 'followers_count': 57, 'profile_sidebar_border_color': 'C0DEED',
                  'profile_use_background_image': True, 'profile_text_color': '333333',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/669282260693213184/rjY5POFU_normal.jpg',
                  'profile_background_tile': False,
                  'description': 'Data, science & maps at @Geographica_GS\n#GIS #python #opensource', 'location': None,
                  'default_profile': True,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/669282260693213184/rjY5POFU_normal.jpg',
                  'follow_request_sent': None, 'geo_enabled': False, 'utc_offset': 7200, 'name': 'Cayetano Benavent V.',
                  'friends_count': 140, 'notifications': None, 'statuses_count': 160, 'favourites_count': 85,
                  'contributors_enabled': False, 'protected': False, 'time_zone': 'Madrid',
                  'default_profile_image': False, 'id_str': '426150795', 'profile_sidebar_fill_color': 'DDEEF6'},
         'contributors': None, 'retweeted_status': {'id': 722445454856822784, 'extended_entities': {'media': [
        {'url': 'https://t.co/N36kmvfW2X', 'id': 722445452151537666,
         'expanded_url': 'http://twitter.com/hectorgeograph/status/722445454856822784/photo/1',
         'id_str': '722445452151537666', 'type': 'photo', 'indices': [119, 142],
         'display_url': 'pic.twitter.com/N36kmvfW2X',
         'sizes': {'thumb': {'resize': 'crop', 'h': 150, 'w': 150}, 'medium': {'resize': 'fit', 'h': 352, 'w': 600},
                   'small': {'resize': 'fit', 'h': 199, 'w': 340}, 'large': {'resize': 'fit', 'h': 601, 'w': 1024}},
         'media_url_https': 'https://pbs.twimg.com/media/CgakT6EWwAIGX3L.jpg',
         'media_url': 'http://pbs.twimg.com/media/CgakT6EWwAIGX3L.jpg'}]}, 'geo': None,
                                                    'text': 'Computing the shortest path on an ellipsoid with Python. Geodesic lines &amp; GIS \nhttps://t.co/3MuJEib6Cu @cayetanobv https://t.co/N36kmvfW2X',
                                                    'retweeted': False, 'in_reply_to_screen_name': None,
                                                    'retweet_count': 1, 'created_at': 'Tue Apr 19 15:23:13 +0000 2016',
                                                    'lang': 'en', 'in_reply_to_user_id': None, 'filter_level': 'low',
                                                    'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                                                    'favorite_count': 1, 'place': None,
                                                    'in_reply_to_status_id_str': None, 'truncated': False,
                                                    'is_quote_status': False, 'in_reply_to_user_id_str': None,
                                                    'favorited': False,
                                                    'user': {'id': 3044644439, 'profile_background_color': '89C9FA',
                                                             'url': 'http://www.geographica.gs',
                                                             'profile_banner_url': 'https://pbs.twimg.com/profile_banners/3044644439/1445360827',
                                                             'screen_name': 'hectorgeograph', 'following': None,
                                                             'listed_count': 88, 'verified': False,
                                                             'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/568088984820015104/bkpfPMLP.png',
                                                             'created_at': 'Wed Feb 18 16:19:17 +0000 2015',
                                                             'lang': 'es', 'profile_link_color': '0084B4',
                                                             'is_translator': False, 'followers_count': 618,
                                                             'profile_sidebar_border_color': 'C0DEED',
                                                             'profile_use_background_image': True,
                                                             'profile_text_color': '333333',
                                                             'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/568088984820015104/bkpfPMLP.png',
                                                             'profile_image_url_https': 'https://pbs.twimg.com/profile_images/577504299464331264/LG5VMtUC_normal.jpeg',
                                                             'profile_background_tile': True,
                                                             'description': 'CEO & Founder Geographica.gs (#GIS #GeoBigData) Data Science, Maps and Sci-Fi enthusiast. EMBA candidate at IE Business School',
                                                             'location': 'SEV/MAD (Spain)', 'default_profile': False,
                                                             'profile_image_url': 'http://pbs.twimg.com/profile_images/577504299464331264/LG5VMtUC_normal.jpeg',
                                                             'follow_request_sent': None, 'geo_enabled': False,
                                                             'utc_offset': None, 'name': 'Héctor García',
                                                             'friends_count': 615, 'notifications': None,
                                                             'statuses_count': 1017, 'favourites_count': 323,
                                                             'contributors_enabled': False, 'protected': False,
                                                             'time_zone': None, 'default_profile_image': False,
                                                             'id_str': '3044644439',
                                                             'profile_sidebar_fill_color': 'DDEEF6'},
                                                    'contributors': None, 'entities': {'symbols': [], 'hashtags': [],
                                                                                       'urls': [{
                                                                                           'display_url': 'blog-geographica.com/2015/06/11/geo…',
                                                                                           'indices': [83,
                                                                                                       106],
                                                                                           'expanded_url': 'http://www.blog-geographica.com/2015/06/11/geodesic-lines-gis/',
                                                                                           'url': 'https://t.co/3MuJEib6Cu'}],
                                                                                       'media': [{
                                                                                           'url': 'https://t.co/N36kmvfW2X',
                                                                                           'id': 722445452151537666,
                                                                                           'expanded_url': 'http://twitter.com/hectorgeograph/status/722445454856822784/photo/1',
                                                                                           'id_str': '722445452151537666',
                                                                                           'type': 'photo',
                                                                                           'indices': [119,
                                                                                                       142],
                                                                                           'display_url': 'pic.twitter.com/N36kmvfW2X',
                                                                                           'sizes': {
                                                                                               'thumb': {
                                                                                                   'resize': 'crop',
                                                                                                   'h': 150,
                                                                                                   'w': 150},
                                                                                               'medium': {
                                                                                                   'resize': 'fit',
                                                                                                   'h': 352,
                                                                                                   'w': 600},
                                                                                               'small': {
                                                                                                   'resize': 'fit',
                                                                                                   'h': 199,
                                                                                                   'w': 340},
                                                                                               'large': {
                                                                                                   'resize': 'fit',
                                                                                                   'h': 601,
                                                                                                   'w': 1024}},
                                                                                           'media_url_https': 'https://pbs.twimg.com/media/CgakT6EWwAIGX3L.jpg',
                                                                                           'media_url': 'http://pbs.twimg.com/media/CgakT6EWwAIGX3L.jpg'}],
                                                                                       'user_mentions': [{
                                                                                           'name': 'Cayetano Benavent V.',
                                                                                           'id': 426150795,
                                                                                           'screen_name': 'cayetanobv',
                                                                                           'id_str': '426150795',
                                                                                           'indices': [
                                                                                               107,
                                                                                               118]}]},
                                                    'in_reply_to_status_id': None, 'possibly_sensitive': False,
                                                    'id_str': '722445454856822784', 'coordinates': None},
         'entities': {'symbols': [], 'hashtags': [], 'urls': [
             {'display_url': 'blog-geographica.com/2015/06/11/geo…', 'indices': [103, 126],
              'expanded_url': 'http://www.blog-geographica.com/2015/06/11/geodesic-lines-gis/',
              'url': 'https://t.co/3MuJEib6Cu'}], 'media': [
             {'id': 722445452151537666, 'source_user_id': 3044644439, 'url': 'https://t.co/N36kmvfW2X', 'type': 'photo',
              'sizes': {'thumb': {'resize': 'crop', 'h': 150, 'w': 150},
                        'medium': {'resize': 'fit', 'h': 352, 'w': 600}, 'small': {'resize': 'fit', 'h': 199, 'w': 340},
                        'large': {'resize': 'fit', 'h': 601, 'w': 1024}}, 'source_user_id_str': '3044644439',
              'source_status_id': 722445454856822784, 'media_url': 'http://pbs.twimg.com/media/CgakT6EWwAIGX3L.jpg',
              'indices': [143, 144],
              'expanded_url': 'http://twitter.com/hectorgeograph/status/722445454856822784/photo/1',
              'media_url_https': 'https://pbs.twimg.com/media/CgakT6EWwAIGX3L.jpg',
              'display_url': 'pic.twitter.com/N36kmvfW2X', 'id_str': '722445452151537666',
              'source_status_id_str': '722445454856822784'}], 'user_mentions': [
             {'name': 'Héctor García', 'id': 3044644439, 'screen_name': 'hectorgeograph', 'id_str': '3044644439',
              'indices': [3, 18]},
             {'name': 'Cayetano Benavent V.', 'id': 426150795, 'screen_name': 'cayetanobv', 'id_str': '426150795',
              'indices': [127, 138]}]}, 'in_reply_to_status_id': None, 'possibly_sensitive': False,
         'id_str': '722453568121348096', 'coordinates': None}"""

tweet2 = {'retweet_count': 0,
          'in_reply_to_status_id': None,
          'user': {'is_translator': False, 'verified': False,
                   'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                   'profile_sidebar_fill_color': 'DDEEF6',
                   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/488689251236593664/pX4JrI1R_normal.png',
                   'time_zone': None, 'id_str': '2645582425',
                   'description': 'Follow this account for PYTHON job tweets from ITJobPro the biggest IT job site on the planet. more at http://www.ITJobPro.com',
                   'geo_enabled': False,
                   'default_profile_image': False,
                   'utc_offset': None,
                   'url': 'http://www.ITJobPro.com',
                   'friends_count': 82, 'name': 'python Jobs',
                   'favourites_count': 0, 'statuses_count': 11424,
                   'profile_background_tile': False,
                   'id': 2645582425, 'lang': 'en',
                   'notifications': None,
                   'profile_text_color': '333333',
                   'default_profile': False, 'listed_count': 54,
                   'profile_background_color': 'FFFFFF',
                   'profile_sidebar_border_color': 'FFFFFF',
                   'created_at': 'Mon Jul 14 14:18:44 +0000 2014',
                   'location': 'Worldwide',
                   'contributors_enabled': False, 'following': None,
                   'profile_link_color': '0151A1',
                   'followers_count': 98, 'protected': False,
                   'follow_request_sent': None,
                   'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                   'screen_name': 'python_job',
                   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2645582425/1405347580',
                   'profile_use_background_image': False,
                   'profile_image_url': 'http://pbs.twimg.com/profile_images/488689251236593664/pX4JrI1R_normal.png'},
          'text': '☆★☆ JOB ALERT ☆★☆ #ITJob #Job #New York - Python Programmer https://t.co/TYcmnopiIo ☜ view full details',
          'id_str': '722498267557208065', 'source': '<a href="http://dlvr.it" rel="nofollow">dlvr.it</a>',
          'truncated': False, 'entities': {'user_mentions': [], 'symbols': [], 'urls': [
        {'url': 'https://t.co/TYcmnopiIo', 'expanded_url': 'http://j.obs.link/L5j9qt', 'indices': [60, 83],
         'display_url': 'j.obs.link/L5j9qt'}], 'hashtags': [{'indices': [18, 24], 'text': 'ITJob'},
                                                            {'indices': [25, 29], 'text': 'Job'},
                                                            {'indices': [30, 34], 'text': 'New'}]}, 'favorited': False,
          'place': None, 'in_reply_to_user_id': None, 'possibly_sensitive': False, 'in_reply_to_status_id_str': None,
          'id': 722498267557208065, 'favorite_count': 0, 'coordinates': None, 'lang': 'en',
          'in_reply_to_user_id_str': None, 'created_at': 'Tue Apr 19 18:53:05 +0000 2016', 'geo': None,
          'timestamp_ms': '1461091985011', 'is_quote_status': False, 'in_reply_to_screen_name': None,
          'retweeted': False, 'contributors': None, 'filter_level': 'low'}
